-- 供应商管理模块数据库脚本

-- 供应商表
CREATE TABLE IF NOT EXISTS `supplier` (
    `id` BIGINT NOT NULL COMMENT '主键ID',
    `code` VARCHAR(50) NOT NULL COMMENT '供应商编码',
    `name` VARCHAR(200) NOT NULL COMMENT '供应商名称',
    `short_name` VARCHAR(100) DEFAULT NULL COMMENT '供应商简称',
    `type` VARCHAR(20) NOT NULL COMMENT '供应商类型: DOMESTIC-国内, OVERSEAS-海外, PROCESSOR-代工厂',
    `status` VARCHAR(20) NOT NULL DEFAULT 'DRAFT' COMMENT '状态: DRAFT-草稿, PENDING_REVIEW-待审核, ACTIVE-已生效, FROZEN-已冻结, TERMINATED-已终止',
    `country` VARCHAR(100) DEFAULT NULL COMMENT '国家',
    `city` VARCHAR(100) DEFAULT NULL COMMENT '城市',
    `address` VARCHAR(500) DEFAULT NULL COMMENT '详细地址',
    `contact_person` VARCHAR(100) DEFAULT NULL COMMENT '联系人',
    `contact_phone` VARCHAR(50) DEFAULT NULL COMMENT '联系电话',
    `contact_email` VARCHAR(100) DEFAULT NULL COMMENT '联系邮箱',
    `tax_number` VARCHAR(50) DEFAULT NULL COMMENT '税号',
    `business_license` VARCHAR(100) DEFAULT NULL COMMENT '营业执照号',
    `bank_name` VARCHAR(200) DEFAULT NULL COMMENT '开户银行',
    `bank_account` VARCHAR(50) DEFAULT NULL COMMENT '银行账号',
    `annual_capacity` DECIMAL(15,2) DEFAULT NULL COMMENT '年产能',
    `main_products` TEXT DEFAULT NULL COMMENT '主要产品',
    `quality_certification` VARCHAR(200) DEFAULT NULL COMMENT '质量认证',
    `iso_certificate` VARCHAR(200) DEFAULT NULL COMMENT 'ISO证书',
    `registered_date` DATE DEFAULT NULL COMMENT '注册日期',
    `annual_review_date` DATE DEFAULT NULL COMMENT '年审日期',
    `evaluation_level` VARCHAR(10) DEFAULT NULL COMMENT '评级: A/B/C/D',
    `delivery_score` INT DEFAULT NULL COMMENT '交货评分',
    `quality_score` INT DEFAULT NULL COMMENT '质量评分',
    `service_score` INT DEFAULT NULL COMMENT '服务评分',
    `comprehensive_score` INT DEFAULT NULL COMMENT '综合评分',
    `create_by` VARCHAR(64) DEFAULT NULL COMMENT '创建者',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` VARCHAR(64) DEFAULT NULL COMMENT '更新者',
    `update_time` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_code` (`code`),
    KEY `idx_status` (`status`),
    KEY `idx_type` (`type`),
    KEY `idx_country` (`country`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='供应商表';
